const Header = () => (
  <navHeader>
    <navContent>
      <nanBarMobile>
        <Link>
          <navLogo
            src=""
            alt=""
          />
        </Link>
        <navMenuItems>
          <navItem>
            <Link>
              <img
                src=""
                alt=""
              />
            </Link>
          </navItem>
          <navItem>
            <Link>
              <img
                src=""
                alt=""
              />
            </Link>
          </navItem>
          <navItem>
            <Link>
              <img
                src=""
                alt=""
              />
            </Link>
          </navItem>
        </navMenuItems>
      </nanBarMobile>
      <navBarDesktop></navBarDesktop>
    </navContent>
  </navHeader>
)